random test to be modified later
unspentspace/unspent.space pull request #2
Opened 2023-07-13 01:16 UTC by midizzz

2023-07-13 01:54 UTC, dragon-foobar commented on content/vault/.obsidian/workspace.json
> +                "file": "BlogPost1.md",
Not sure why you need to do this?

2023-07-13 01:55 UTC, dragon-foobar commented on content/vault/BlogPost1.md
> +
I like what you've done here, but maybe you could customise the blog to make it unique ?

2023-07-13 01:56 UTC, dragon-foobar requested changes
hmm.. good first try dude. Maybe you could write an article that isn't the same as welcome.

2023-07-18 00:16 UTC, unspentspace-admin commented on content/vault/BlogPost1.md
> +# MultiSig Magic Trust Machine
Nice title!

2023-07-18 00:19 UTC, unspentspace-admin commented
Awesome, man. Just a few spelling/grammar things. Maybe easier if I add a commit on? @midizzz

2023-07-18 00:22 UTC, midizzz commented
> Awesome, man. Just a few spelling/grammar things. Maybe easier if I add a commit on? @midizzz 

Yeah. I want to submit again. Then you can proof it. Still to ruff. Just testing the method. Seems it works

2023-07-20 02:03 UTC, midizzz commented
ok, not sure if I am typing in the right place.. It looks like you have seen this, maybe there's somthing about a tag "satoshis place"? no idea. There must be some typos etc?

2023-07-20 02:05 UTC, dragon-foobar commented
@midizzz there are a couple of typos still, but that's not the main issue. The main issue is that your branch is now not in harmony with the main branch. You need to merge dev branch into your branch. We can do a screen share or something.

2023-07-20 02:18 UTC, midizzz commented
tbh at the moment if feels like the communication here falls into black hole

2023-08-12 18:53 UTC, nickfarrow commented
Rebased and removed excess changes (DS_STORE and obsidian changes)

I also did a proof read, with a solid amount of wording changes and grammar fixes. Inspiring post, I want to start a peer multisig now. Please check I have accurately captured your words 0b117ce4a05ab624553914c996de2242165877a4

2023-08-14 02:44 UTC, midizzz commented
Thanks @nickfarrow .. Oh no. I have also reviewed this cutting it down a lot and have been trying to resubmit. I am just getting used to the Obsidian to Github flow here.. I better have a look at your edits in context of the new revision named Magic MultiSig Trust Machine.

2023-08-14 10:10 UTC, closed without merging